### ISSUE TITLE
DAG environnement not beeing cleaned

### ISSUE THREAD

**Issue by vsivadon** [maltezfaria/DataFlowTasks.jl#24]
The scenario :
- During developpement, we let a mistake in a DFT task -> when we try to execute the code, the task fails.
- We fix the mistake, and try again -> the code will be stuck in the DataFlowTasks.sync() function, that will wait for the failed task of the previous run.
We now have to restart the REPL.

In the next code snippet, run a first time with the "fail" task, and a second time with the "succeed", the 2nd run will be stuck in the synchronisation point.

```julia
using DataFlowTasks
import DataFlowTasks as DFT

function fail(A)
    @dspawn (A[0] += 1)
end

function success(A)
    @dspawn (A[1] += 1)
end

A = rand(2)
fail(A)  # -> success(A)
DFT.sync()
```

**Comment by maltezfaria** [comment]
Besides re-throwing the errors generated by tasks so that we can print it a the top level, I don't see much else that can be done here. Maybe we could have `DFG.sync` also check for errors, but I don't think it is worth it.

**Comment by ffevotte** [comment]
Could we have a function that somehow empties the DAG? Or kills all tasks remaining in a waiting state? I think that could be useful in order to avoid having to restart the REPL (which is currently the only way to re-start with a clean DAG if I'm not mistaken)

**Comment by vsivadon** [comment]
I added this function yesterday :

```julia
function reset!()
    dag = getscheduler().dag

    for pair ∈ dag.inoutlist
        node = pair.first
        try
            wait(node)
        catch
            remove_node!(dag, node)
        end
    end

    sync()
    resetlogger!()
    resetcounter!()
end
```

There's a bit of hacking, because emptying the DAG poses 2 problems :
* If we don't wait a task before trying to remove it from the DAG, it might crash
* If we wait a failed task, it crashes

It works though. I thought that that function could replace the "resetlogger!()" call that i often recommend using in the doc, this time this function really do reset DataFlowTasks environnement.

**Comment by maltezfaria** [comment]
The question for me here is: what do we want to happen if a task fails in the `DAG`? Yes, you can manually empty the dag, reset the scheduler, or change the scheduler altogether with `setscheduler`, but I am not sure what the appropriate way to error is here...

**Comment by vsivadon** [comment]
In the scenario i described, when you first run the task that contains the error, it shows the message in the REPL. You can now fix it. But without this function you're stuck : you have to restart the REPL because de failed task is still in the environnement, and so it will affect the next runs. This way we can restart from the beginning. So it's not really a way of handling the error, but more a cleaning tool.

**Comment by maltezfaria** [comment]
Ok, I think I get now what the issue is: one of the tasks created errored, the message was shown on the REPL so the user is fully aware that something went wrong, and he/she now wants a functionality to reset things without restarting the REPL. I agree, a function for that would be nice to have. 

One thing that we have to be carefully about is to properly clear all underlying `Task`s to avoid having data that cannot be GC'ed because some task which is never going to be scheduled references it. Let me take a crack at this and I will ask for a review.

**Comment by ffevotte** [comment]
Agreed!

Implementation-wise, note that [`handle_errors()`](https://github.com/maltezfaria/DataFlowTasks.jl/blob/main/src/utils.jl#L47-L59) allows stopping a `DataFlowTask` simply using:
```
schedule(task, :stop, error=true)
```

But this will only be "clean" in debug mode (otherwise, there is no `try...catch` block in order to avoid any runtime penalty that could be associated to it). That may be the behavior we want anyway: it's probably not that much of a problem if stopped tasks produce error messages in no-debug mode (especially since it will be kinda hard for users to see them).
